#!/usr/bin/env bash
# Convert a dotenv file into secrets.auto.tfvars (gitignored), then terraform plan.
# Never runs terraform apply — apply is always a separate manual step.
set -euo pipefail

usage() {
  cat <<'EOF'
Usage: ./scripts/sync-orion-env.sh <path-to-dotenv>

Reads KEY=VALUE pairs from the given file, writes secrets.auto.tfvars in the
Terraform project root (allowlisted Orion keys only), then runs terraform plan.

Does not run terraform apply.
EOF
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  usage
  exit 0
fi

if [[ $# -lt 1 ]]; then
  usage
  exit 1
fi

ENV_FILE="$1"
if [[ ! -f "$ENV_FILE" ]]; then
  echo "error: file not found: $ENV_FILE" >&2
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TF_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
OUT_FILE="${TF_ROOT}/secrets.auto.tfvars"

# Allowlists — keep in sync with variables.tf validation blocks.
SECRET_KEYS="JWT_SECRET POSTGRES_PASSWORD POSTGRES_USER POSTGRES_DB"
# POSTGRES_HOST is optional: Terraform overrides it from Cloud SQL private IP.
PLAIN_KEYS="POSTGRES_HOST POSTGRES_PORT POSTGRES_SSLMODE PGSSLMODE JWT_EXPIRY_MINUTES BCRYPT_COST AUTH_ENABLED"
IGNORE_KEYS="PORT"

# Parsed values stored as KEY=VALUE lines (bash 3.2 compatible; no associative arrays).
PARSED=""

is_in() {
  local needle="$1"
  local haystack="$2"
  local x
  for x in $haystack; do
    if [[ "$x" == "$needle" ]]; then
      return 0
    fi
  done
  return 1
}

get_val() {
  local want="$1"
  local line key val
  while IFS= read -r line; do
    [[ -z "$line" ]] && continue
    key="${line%%=*}"
    val="${line#*=}"
    if [[ "$key" == "$want" ]]; then
      printf '%s' "$val"
      return 0
    fi
  done <<EOF
$PARSED
EOF
  return 1
}

has_key() {
  local want="$1"
  local line key
  while IFS= read -r line; do
    [[ -z "$line" ]] && continue
    key="${line%%=*}"
    if [[ "$key" == "$want" ]]; then
      return 0
    fi
  done <<EOF
$PARSED
EOF
  return 1
}

# Escape a value for a double-quoted HCL string.
hcl_escape() {
  local s=$1
  s=${s//\\/\\\\}
  s=${s//\"/\\\"}
  s=${s//$'\n'/\\n}
  s=${s//$'\r'/\\r}
  s=${s//$'\t'/\\t}
  printf '%s' "$s"
}

while IFS= read -r line || [[ -n "$line" ]]; do
  line="${line%$'\r'}"
  # skip blank / comment
  case "$line" in
    ''|\#*) continue ;;
  esac
  # also skip whitespace-only and leading-comment after spaces
  trimmed="${line#"${line%%[![:space:]]*}"}"
  [[ -z "$trimmed" ]] && continue
  [[ "$trimmed" == \#* ]] && continue

  if [[ ! "$line" =~ ^[[:space:]]*([A-Za-z_][A-Za-z0-9_]*)=(.*)$ ]]; then
    echo "warning: skipping unparseable line" >&2
    continue
  fi

  key="${BASH_REMATCH[1]}"
  val="${BASH_REMATCH[2]}"

  if [[ "$val" =~ ^\"(.*)\"$ ]]; then
    val="${BASH_REMATCH[1]}"
  elif [[ "$val" =~ ^\'(.*)\'$ ]]; then
    val="${BASH_REMATCH[1]}"
  fi

  if is_in "$key" "$IGNORE_KEYS"; then
    continue
  fi

  if is_in "$key" "$SECRET_KEYS" || is_in "$key" "$PLAIN_KEYS"; then
    # replace existing key if re-defined
    if has_key "$key"; then
      new_parsed=""
      while IFS= read -r pline; do
        [[ -z "$pline" ]] && continue
        pkey="${pline%%=*}"
        if [[ "$pkey" != "$key" ]]; then
          new_parsed="${new_parsed}${pline}"$'\n'
        fi
      done <<EOF
$PARSED
EOF
      PARSED="$new_parsed"
    fi
    PARSED="${PARSED}${key}=${val}"$'\n'
    continue
  fi

  echo "warning: ignoring unknown key (not in allowlist): $key" >&2
done < "$ENV_FILE"

missing=0
for key in $SECRET_KEYS; do
  if ! has_key "$key"; then
    echo "error: required secret key missing: $key" >&2
    missing=1
    continue
  fi
  v="$(get_val "$key")"
  if [[ -z "$v" ]]; then
    echo "error: required secret key empty: $key" >&2
    missing=1
  fi
done
if [[ "$missing" -ne 0 ]]; then
  exit 1
fi

tmp="$(mktemp "${TF_ROOT}/.secrets.auto.tfvars.XXXXXX")"
cleanup() { rm -f "$tmp"; }
trap cleanup EXIT

{
  echo "# Generated by scripts/sync-orion-env.sh — do not commit."
  echo "# Source path recorded without values."
  echo
  echo "orion_secrets = {"
  for key in $SECRET_KEYS; do
    printf '  %s = "%s"\n' "$key" "$(hcl_escape "$(get_val "$key")")"
  done
  echo "}"
  echo
  echo "orion_env = {"
  for key in $PLAIN_KEYS; do
    if has_key "$key"; then
      printf '  %s = "%s"\n' "$key" "$(hcl_escape "$(get_val "$key")")"
    fi
  done
  echo "}"
} > "$tmp"

chmod 600 "$tmp"
mv -f "$tmp" "$OUT_FILE"
chmod 600 "$OUT_FILE"
trap - EXIT

echo "wrote ${OUT_FILE} (mode 600)"
echo "running terraform plan (apply is manual)..."
cd "$TF_ROOT"
terraform plan
