packer {
  required_plugins {
    vmware = {
      version = ">= 1.0"
      source  = "github.com/hashicorp/vmware"
    }
    ansible = {
      version = ">= 1.1"
      source  = "github.com/hashicorp/ansible"
    }
    vagrant = {
      version = ">= 1.1"
      source  = "github.com/hashicorp/vagrant"
    }
  }
}

# ---------------------------------------------------------------------------
# Variables — sourced from env (PKR_VAR_*) or .pkrvars.hcl
# ---------------------------------------------------------------------------

variable "iso_url" {
  type        = string
  default     = env("LINUX_ISO_PATH") != "" ? "${env("LINUX_ISO_PATH")}/ubuntu-26.04-desktop-arm64.iso" : ""
  description = "Path or URL to the Ubuntu Desktop ISO"
}

variable "iso_checksum" {
  type        = string
  default     = "none"
  description = "SHA256 checksum of the ISO (set 'none' to skip)"
}

variable "initial_user" {
  type        = string
  default     = env("INITIAL_USER") != "" ? env("INITIAL_USER") : "samworker"
  description = "Initial user created during autoinstall"
}

variable "ssh_password" {
  type        = string
  sensitive   = true
  default     = "packer"
  description = "Temporary password for Packer SSH (rotated post-build)"
}

variable "ssh_password_hash" {
  type        = string
  sensitive   = true
  description = "SHA-512 hash of ssh_password for cloud-init identity (generated by packer.sh)"
}

variable "vm_name" {
  type    = string
  default = "buntoo2604-desk"
}

variable "output_directory" {
  type    = string
  default = "output-tmp"
}

variable "cpus" {
  type    = number
  default = 4
}

variable "memory" {
  type    = number
  default = 8192
}

variable "disk_size" {
  type    = number
  default = 81920
}

variable "allowed_subnet" {
  type        = string
  default     = env("ALLOWED_SUBNET") != "" ? env("ALLOWED_SUBNET") : "192.168.1.0/24"
  description = "CIDR subnet permitted for SSH access"
}

# ---------------------------------------------------------------------------
# Source — VMware ISO builder (Fusion on macOS)
# ---------------------------------------------------------------------------

source "vmware-iso" "ubuntu-desktop" {
  iso_url      = var.iso_url
  iso_checksum = var.iso_checksum

  vm_name          = var.vm_name
  output_directory = var.output_directory
  guest_os_type    = "arm-ubuntu-64"
  version          = "21"

  cpus      = var.cpus
  memory    = var.memory
  disk_size = var.disk_size

  network_adapter_type = "vmxnet3"
  usb                  = false
  disk_adapter_type    = "nvme"

  vmx_data = {
    "firmware"                       = "efi"
    "bios.bootDelay"                 = "3000"
    "uefi.secureBoot.enabled"        = "false"
    "svga.autodetect"                = "true"
    "mks.enable3d"                   = "true"
    "gui.fitGuestUsingNativeDisplayResolution" = "true"
  }

  # Cloud-init served via Packer's built-in HTTP server
  http_content = {
    "/user-data" = templatefile("${path.root}/http/user-data.pkrtpl.hcl", {
      username      = var.initial_user
      password_hash = var.ssh_password_hash
      hostname      = var.vm_name
    })
    "/meta-data" = file("${path.root}/http/meta-data")
  }

  ssh_username     = var.initial_user
  ssh_password     = var.ssh_password
  ssh_timeout      = "1h"
  shutdown_command  = "echo '${var.ssh_password}' | sudo -S shutdown -P now"

  skip_compaction = false
  boot_wait       = "5s"
  boot_key_interval = "50ms"
  

  boot_command = [
    "c", "<wait>",
    "linux /casper/vmlinuz autoinstall ds='nocloud-net;s=http://{{ .HTTPIP }}:{{ .HTTPPort }}/' ---", "<enter><wait>",
    "initrd /casper/initrd", "<enter><wait>",
    "boot", "<enter>"
  ]
}

# ---------------------------------------------------------------------------
# Build
# ---------------------------------------------------------------------------

build {
  sources = ["source.vmware-iso.ubuntu-desktop"]

  # --- Stage 1: Bootstrap for Ansible ---
  provisioner "shell" {
    execute_command = "echo '${var.ssh_password}' | sudo -S bash -c '{{ .Path }}'"
    inline = [
      "cloud-init status --wait || true",
      "apt-get update -qq",
      "apt-get install -y -qq python3 python3-apt openssh-server",
      "systemctl enable --now ssh"
    ]
  }

  # --- Stage 2: Hardening + Desktop via Ansible ---
  provisioner "ansible" {
    playbook_file = "./packer-provision.yml"
    user          = var.initial_user
    extra_arguments = [
      "--extra-vars", "initial_user=${var.initial_user} allowed_subnet=${var.allowed_subnet}"
    ]
  }

  # --- Stage 3: Lock down SSH + cleanup for image shrink ---
  provisioner "shell" {
    execute_command = "echo '${var.ssh_password}' | sudo -S bash -c '{{ .Path }}'"
    inline = [
      # Bind SSH to localhost only — unreachable from external network
      # Vagrant connects via port forward (host 127.0.0.1:2223 → guest :22)
      "echo 'ListenAddress 127.0.0.1' >> /etc/ssh/sshd_config",
      "echo 'ListenAddress ::1' >> /etc/ssh/sshd_config",
      # UFW: remove any broad SSH allow, permit only loopback + Vagrant NAT
      "ufw delete allow 22/tcp 2>/dev/null || true",
      "ufw allow from 127.0.0.1 to any port 22",
      "ufw allow from 10.0.2.0/24 to any port 22",
      "apt-get -y autoremove --purge",
      "apt-get -y clean",
      "rm -rf /tmp/* /var/tmp/*",
      "truncate -s 0 /var/log/**/*.log || true",
      "dd if=/dev/zero of=/EMPTY bs=1M 2>/dev/null || true",
      "rm -f /EMPTY",
      "sync"
    ]
  }

  # --- Post-processor: export as Vagrant box ---
  post-processor "vagrant" {
    provider_override = "vmware"
    output            = "output-desktop/${var.vm_name}.box"
  }
}