Vagrant.configure("2") do |config|
  config.vm.provider "vmware_desktop" do |v|
    v.vmx["numvcpus"] = "4"
    v.vmx["memsize"]  = "8192"
    v.gui = false
  end
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "full-hardening.yml"
  end
end
